baseUrl: https://alex.loghin.dev
languageCode: en-us
theme: hello-friend
paginate: 3

params:
  contentTypeName: ledger
  defaultTheme: dark
  showMenuItems: 2
  rssFullText: true
  mainSections:
    - ledger

outputs:
  home:
    - HTML
    - RSS
  page:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML

languages:
  en:
    title: Loghin Alexandru
    author:
      name: Loghin Alexandru
      email: alex.loghin@outlook.com
      github: https://github.com/loghinalexandru
      linkedin: https://www.linkedin.com/in/loghinalexandru
    keywords: tech,opensource,blog
    copyright: Copyright © 2024 Loghin Alexandru | Powered By Hugo
    menuMore: Show more
    writtenBy: Crafted by
    readMore: Read more
    minuteReadingTime: min read
    indexOlderPosts: Checkout all posts
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    dateFormatSingle: 2006-01-02
    dateFormatList: 2006-01-02
    params:
      logo:
        logoText: cat ~/.home
        logoHomeLink: /
    menu:
      main:
        - identifier: about
          name: About
          url: /about
        - identifier: ledger
          name: Ledger
          url: /ledger
