baseUrl: https://loghinalexandru.com
languageCode: en-us
theme: hello-friend
paginate: 5

params:
  contentTypeName: posts
  defaultTheme: dark
  showMenuItems: 3
  rssFullText: true
  mainSections:
    - projects
    - posts

outputs:
  home:
    - HTML
    - RSS
  page:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML

languages:
  en:
    title: Loghin Alexandru
    author:
      name: Loghin Alexandru
      email: alex.loghin@outlook.com
    keywords: tech,opensource,blog
    copyright: Copyright © 2022 Loghin Alexandru | Powered By Hugo
    menuMore: Show more
    writtenBy: Crafted by
    readMore: Read more
    minuteReadingTime: min read
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    dateFormatSingle: 2006-01-02
    dateFormatList: 2006-01-02
    params:
      logo:
        logoText: cat ~/.home
        logoHomeLink: /
    menu:
      main:
        - identifier: about
          name: About
          url: /about
        - identifier: projects
          name: Projects
          url: /projects
        - identifier: posts
          name: Ledger
          url: /posts
